import { useConfiguracionStore } from '../stores/configuracionStore'

const translations = {
  es: {
    // Menú y Layout
    menu: 'Menú',
    dashboard: 'Dashboard',
    citas: 'Citas',
    clientes: 'Clientes',
    servicios: 'Servicios',
    empleados: 'Empleados',
    configuracion: 'Configuración',
    cerrarSesion: 'Cerrar Sesión',
    usuario: 'Usuario',
    modoClaro: 'Modo claro',
    modoOscuro: 'Modo oscuro',
    sistemaGestion: 'Sistema de Gestión',
    modoDemoActivo: 'Modo Demo Activo',
    usaCredencialesDemo: 'Usa:',
    
    // Dashboard
    miCalendario: 'Mi Calendario',
    resumenGeneral: 'Resumen general del negocio',
    bienvenido: 'Bienvenido',
    cargandoDatos: 'Cargando datos...',
    miGanancias: 'Mis Ganancias',
    comision: 'de comisión',
    citasEstaSemana: 'Citas Esta Semana',
    completadas: 'completadas',
    confirmadas: 'Confirmadas',
    pendientes: 'pendientes',
    calendario: 'Calendario',
    calendarioSemanal: 'Calendario Semanal',
    sinCitas: 'Sin citas',
    ganancia: 'Ganancia',
    ingresosHoy: 'Ingresos Hoy',
    citasCompletadasLabel: 'citas completadas',
    proximasCitasHoy: 'Próximas Citas de Hoy',
    verTodas: 'Ver todas',
    noCitasHoy: 'No hay citas programadas para hoy',
    estadoCitas: 'Estado de Citas',
    totalHoy: 'Total Hoy',
    accesosRapidos: 'Accesos Rápidos',
    verServicios: 'Ver Servicios',
    verEmpleados: 'Ver Empleados',
    verClientes: 'Ver Clientes',
    
    // Formularios
    nombre: 'Nombre',
    nombreCompleto: 'Nombre Completo',
    email: 'Email',
    correoElectronico: 'Correo electrónico',
    telefono: 'Teléfono',
    placeholderTelefono: 'Ej: 555-1234',
    direccion: 'Dirección',
    descripcion: 'Descripción',
    moneda: 'Moneda',
    formatoFecha: 'Formato Fecha',
    zonaHoraria: 'Zona Horaria',
    idioma: 'Idioma',
    activo: 'Activo',
    inactivo: 'Inactivo',
    estado: 'Estado',
    registro: 'Registro',
    contacto: 'Contacto',
    acciones: 'Acciones',
    visita: 'visita',
    visitas: 'visitas',
    ultimaVisita: 'Última',
    notas: 'Notas',
    opcional: 'Opcional',
    placeholderNotasCliente: 'Agregar notas adicionales sobre el cliente...',
    
    // Botones
    guardar: 'Guardar',
    guardarConfiguracion: 'Guardar Configuración',
    cancelar: 'Cancelar',
    cerrar: 'Cerrar',
    eliminar: 'Eliminar',
    editar: 'Editar',
    crear: 'Crear',
    crearCita: 'Crear Cita',
    crearCliente: 'Crear Cliente',
    crearServicio: 'Crear Servicio',
    crearEmpleado: 'Crear Empleado',
    buscar: 'Buscar',
    nueva: 'Nueva',
    nuevaCita: 'Nueva Cita',
    registrarse: 'Registrarse',
    registrando: 'Registrando...',
    iniciarSesion: 'Iniciar Sesión',
    iniciandoSesion: 'Iniciando sesión...',
    recuperar: 'Recuperar',
    olvidasteContrasena: '¿Olvidaste tu contraseña?',
    noTienesCuenta: '¿No tienes cuenta?',
    crearCuenta: 'Crear Cuenta',
    rol: 'Rol',
    admin: 'Administrador',
    recepcionista: 'Recepcionista',
    barbero: 'Barbero',
    placeholderEmail: 'usuario@ejemplo.com',
    placeholderNombre: 'Ej: Juan Pérez',
    placeholderEmailRegistro: 'Ej: juan@email.com',
    placeholderContrasena: 'Mínimo 6 caracteres',
    completarCampos: 'Por favor completa todos los campos',
    errorIniciarSesion: 'Error al iniciar sesión',
    errorRegistro: 'Error al registrarse',
    datosDemo: 'o',
    
    // Citas
    cliente: 'Cliente',
    empleado: 'Empleado',
    servicio: 'Servicio',
    hora: 'Hora',
    dia: 'Día',
    duracion: 'Duración',
    precio: 'Precio',
    detallesCita: 'Detalles de la Cita',
    disponibilidadPersonal: 'Disponibilidad del Personal',
    proximasCitas: 'Próximas Citas',
    horasDias: 'Hora - Dias',
    conflicto: 'Conflicto',
    
    // Configuración
    informacionNegocio: 'Información del Negocio',
    configuracionGeneral: 'Configuración General',
    notificaciones: 'Notificaciones',
    recordatorioCitas: 'Recordatorio de Citas',
    confirmacionAutomatica: 'Confirmación Automática',
    recordatorioHoras: 'Recordatorio Horas Antes',
    
    // Estados
    error: 'Error',
    exito: 'Éxito',
    cargando: 'Cargando...',
    guardando: 'Guardando...',
    confirmado: 'CONFIRMADO',
    pendiente: 'PENDIENTE',
    cancelado: 'CANCELADO',
    completado: 'COMPLETADO',
    completada: 'COMPLETADA',
    cancelada: 'CANCELADA',
    
    // Mensajes
    guardarExitoso: 'guardada correctamente',
    errorAlGuardar: 'Error al guardar',
    requieroCamposObligatorios: 'Todos los campos con * son obligatorios',
    actualizar: 'Actualizar',
    nuevoCliente: 'Nuevo Cliente',
    editarCliente: 'Editar Cliente',
    clientesTitulo: 'Clientes',
    clientesSubtitulo: 'Administra la información de tus clientes',
    totalClientes: 'Total Clientes',
    clientesActivos: 'Clientes Activos',
    visitasTotales: 'Visitas Totales',
    visitasPromedio: 'Promedio Visitas',
    placeholderBuscarClientes: 'Buscar por nombre, teléfono o email...',
    cargandoClientes: 'Cargando clientes...',
    sinResultadosClientes: 'No se encontraron clientes',
    sinClientes: 'No hay clientes registrados',
    confirmarEliminarCliente: '¿Estás seguro de eliminar este cliente?',
    confirmarEliminarEmpleado: '¿Estás seguro de eliminar este empleado?',
    clienteNuevoBadge: 'Cliente nuevo',
    clienteRegularBadge: 'Cliente regular',
    clienteFrecuenteBadge: '⭐ Cliente frecuente',
    clienteVipBadge: '⭐ VIP Cliente',
    nuevoClienteModal: 'Nuevo Cliente',
    editarClienteModal: 'Editar Cliente',
    guardandoClienteError: 'Error al crear cliente',
    guardandoEmpleadoError: 'Error al crear empleado',

    // Servicios
    serviciosTitulo: 'Servicios',
    serviciosSubtitulo: 'Administra los servicios y precios de la barbería',
    totalServiciosLabel: 'Total Servicios',
    precioPromedio: 'Precio Promedio',
    duracionPromedio: 'Duración Promedio',
    resultados: 'Resultados',
    placeholderBuscarServicios: 'Buscar por nombre, descripción o categoría...',
    todasCategorias: '🏷️ Todas las categorías',
    cargandoServicios: 'Cargando servicios...',
    sinResultadosServicios: 'No se encontraron servicios',
    sinServicios: 'No hay servicios registrados',
    precioLabel: 'Precio',
    duracionLabel: 'Duración',
    nombreServicio: 'Nombre del Servicio',
    categoria: 'Categoría',
    descripcionServicio: 'Descripción (Opcional)',
    servicioActivo: 'Servicio activo',
    nuevoServicio: 'Nuevo Servicio',
    editarServicio: 'Editar Servicio',
    placeholderServicioNombre: 'Ej: Corte Clásico',
    placeholderPrecio: '0.00',
    placeholderDuracion: '30',
    placeholderDescripcionServicio: 'Agregar una descripción del servicio...',
    confirmarEliminarServicio: '¿Estás seguro de eliminar este servicio?',
    errorCrearServicio: 'Error al crear servicio',
    errorActualizarServicio: 'Error al actualizar servicio',

    // Empleados
    empleadosTitulo: 'Personal',
    empleadosSubtitulo: 'Administra el personal de la barbería',
    totalPersonal: 'Total Personal',
    barberos: 'Barberos',
    recepcionistas: 'Recepcionistas',
    placeholderBuscarEmpleados: 'Buscar por nombre, email, teléfono...',
    todosRoles: '🛡️ Todos los roles',
    cargandoEmpleados: 'Cargando empleados...',
    sinResultadosEmpleados: 'No se encontraron empleados',
    sinEmpleados: 'No hay empleados registrados',
    nuevoEmpleado: 'Nuevo Empleado',
    editarEmpleado: 'Editar Empleado',
    passwordRequeridaEmpleado: 'La contraseña es requerida para crear un nuevo empleado',
    errorCrearEmpleado: 'Error al crear empleado',
    errorActualizarEmpleado: 'Error al actualizar empleado',
    contrasena: 'Contraseña',
    mostrarContrasena: 'Mostrar contraseña',
    ocultarContrasena: 'Ocultar contraseña',
    dejarVacioMantener: 'Dejar vacío para mantener la actual',
    minimo6Caracteres: 'Mínimo 6 caracteres',
    contrasenaActual: 'Contraseña actual',
    ingresarNuevaContrasena: 'Ingresa una nueva contraseña para cambiar la actual',
    ingresarContrasenaNuevoEmpleado: 'Ingresa la contraseña para el nuevo empleado',
    fechaContratacion: 'Fecha de Contratación',
    porcentajeComision: 'Porcentaje de Comisión (%)',
    especialidad: 'Especialidad',
    empleadoActivo: 'Empleado activo',
    soloLectura: 'Solo lectura',
    soloPuedesCrear: 'Solo puedes crear nuevos empleados',

    // Dashboard adicionales
    ingresos: 'Ingresos',
    citasCompletadasTexto: 'citas completadas',
    verTodasArrow: 'Ver todas →',
    nuevaCitaBtn: 'Nueva Cita',
    nuevaCitaRapida: '📅 Nueva Cita',
    nuevoClienteRapido: '👥 Nuevo Cliente',
    verServiciosRapido: '✂️ Ver Servicios',
    verEmpleadosRapido: '👨‍💼 Ver Empleados',
    citasHoyLabel: 'Citas Hoy',
    
    // Nuevas claves para Citas y Configuración
    citasTitulo: 'Citas',
    citasSubtitulo: 'Gestiona tus citas y horarios',
    editarCita: 'Editar Cita',
    buscarCliente: 'Buscar Cliente',
    buscarClientePlaceholder: 'Buscar por nombre, teléfono o email...',
    crearNuevoCliente: '➕ Crear Nuevo Cliente',
    serviciosLabel: 'Servicios',
    estadoLabel: 'Estado',
    notasLabel: 'Notas',
    agregarNotas: 'Agregar notas adicionales...',
    seleccionarBarbero: 'Seleccionar barbero...',
    seleccionarServicio: 'Debes seleccionar al menos un servicio',
    seleccionarCliente: 'Debes seleccionar un cliente',
    barberoRequerido: 'Debes seleccionar un barbero',
    nombreYTelefonoRequeridos: 'Nombre y teléfono son requeridos',
    nombreCompletoPlaceholder: 'Ej: Juan Pérez',
    telefonoPlaceholder: 'Ej: 555-1234',
    emailOpcional: 'Email (Opcional)',
    emailPlaceholder: 'Ej: juan@email.com',
    cancelarBtn: 'Cancelar',
    eliminarBtn: 'Eliminar',
    actualizarBtn: 'Actualizar',
    guardarBtn: 'Guardar',
    fechaYHora: 'Fecha y Hora',
    barberoLabel: 'Barbero',
    barberoDisponiblidad: 'Disponibilidad del Personal',
    filtrarPorBarbero: '🔍 Filtrar por Barbero',
    todosBarberos: '👥 Todos los barberos',
    limpiarFiltro: '✕ Limpiar filtro',
    mostrando: 'Mostrando citas de:',
    citasEnEstaSemana: 'citas en esta semana',
    misCitas: '📋 Mis Citas',
    disponible: '✅ Disponible',
    variosBarberos: '💡 Múltiples Barberos',
    variosBarberosDescripcion: 'Varios barberos pueden trabajar simultáneamente en el mismo horario. Las citas se muestran lado a lado en la misma celda del calendario.',
    barberoTieneConflicto: 'El barbero ya tiene una cita con',
    aOtroCliente: 'otro cliente',
    deTiempoA: 'de',
    porFavorSelecciona: 'Por favor, selecciona otro horario o barbero.',
    errorAlCrearCita: 'Error al crear cita',
    errorAlActualizarCita: 'Error al actualizar cita',
    estasSeguroEliminarCita: '¿Estás seguro de eliminar esta cita?',
    confirmada: 'Confirmada',
    enProceso: 'En Proceso',
    noAsistio: 'No Asistió',
    
    // Configuración
    horariosDeTrabajos: 'Horarios de Trabajo',
    configuraLasHoras: 'Configura las horas de apertura y cierre de la barbería para cada día de la semana',
    tableDia: 'Día',
    tableApertura: 'Apertura',
    tableCierre: 'Cierre',
    tableEstado: 'Estado',
    tableAcciones: 'Acciones',
    guardarHorarios: '💾 Guardar Horarios',
    horariosGuardadosCorrectamente: 'Horarios guardados correctamente',
    errorGuardarHorarios: 'Error al guardar los horarios',
    informacionNegocioTabla: '🏢 Información del Negocio',
    administraLaInformacion: 'Administra la información básica de tu barbería',
    nombreDelNegocio: 'Nombre del Negocio *',
    nombreDelNegocioRequerido: 'El nombre del negocio es requerido',
    descripcionBreve: 'Descripción breve del negocio...',
    guardarInformacion: '💾 Guardar Información',
    informacionGuardada: 'Información del negocio guardada correctamente',
    configurationGeneral: '⚙️ Configuración General',
    configurarPreferencias: 'Configura las preferencias generales del sistema',
    monedaEtiqueta: 'Moneda *',
    formatoFechaEtiqueta: 'Formato de Fecha *',
    zonaHorariaEtiqueta: 'Zona Horaria *',
    idiomaEtiqueta: 'Idioma *',
    configGeneralGuardada: 'Configuración general guardada correctamente',
    configNotificaciones: '🔔 Configuración de Notificaciones',
    configurarNotificaciones: 'Configura cómo y cuándo se envían las notificaciones',
    enviarRecordatoriosCitas: '⏰ Enviar recordatorios de citas',
    horasAntesLaCita: 'Horas antes de la cita para enviar el recordatorio (máximo 168 horas = 7 días)',
    configNotificacionesGuardada: 'Configuración de notificaciones guardada correctamente',
    estasSeguroRestaurar: '¿Estás seguro de restaurar los horarios predeterminados?',
    lunesLabel: 'Lunes',
    martesLabel: 'Martes',
    miercolesLabel: 'Miércoles',
    juevesLabel: 'Jueves',
    viernesLabel: 'Viernes',
    sabadoLabel: 'Sábado',
    domingoLabel: 'Domingo',
    soloAdminsPueden: 'Solo los administradores pueden acceder',
    abierto: 'Abierto',
    cerrado: 'Cerrado',
    aplicarATodos: '📋 Aplicar a todos',
    aplicarEsteHorario: 'Aplicar este horario a todos los días',
    restaurarPredeterminados: '🔄 Restaurar predeterminados',
  },
  en: {
    // Menu y Layout
    menu: 'Menu',
    dashboard: 'Dashboard',
    citas: 'Appointments',
    clientes: 'Clients',
    servicios: 'Services',
    empleados: 'Employees',
    configuracion: 'Settings',
    cerrarSesion: 'Logout',
    usuario: 'User',
    modoClaro: 'Light mode',
    modoOscuro: 'Dark mode',
    sistemaGestion: 'Management System',
    modoDemoActivo: 'Demo Mode Active',
    usaCredencialesDemo: 'Use:',
    
    // Dashboard
    miCalendario: 'My Calendar',
    resumenGeneral: 'Business Overview',
    bienvenido: 'Welcome',
    cargandoDatos: 'Loading data...',
    miGanancias: 'My Earnings',
    comision: 'commission',
    citasEstaSemana: 'This Week Appointments',
    completadas: 'completed',
    confirmadas: 'Confirmed',
    pendientes: 'pending',
    calendario: 'Calendar',
    calendarioSemanal: 'Weekly Calendar',
    sinCitas: 'No appointments',
    ganancia: 'Earnings',
    ingresosHoy: 'Today\'s Revenue',
    citasCompletadasLabel: 'completed appointments',
    proximasCitasHoy: 'Today\'s Upcoming Appointments',
    verTodas: 'See all',
    noCitasHoy: 'No appointments scheduled for today',
    estadoCitas: 'Appointment Status',
    totalHoy: 'Total Today',
    accesosRapidos: 'Quick Actions',
    verServicios: 'View Services',
    verEmpleados: 'View Staff',
    verClientes: 'View Clients',
    
    // Formularios
    nombre: 'Name',
    nombreCompleto: 'Full Name',
    email: 'Email',
    correoElectronico: 'Email address',
    telefono: 'Phone',
    placeholderTelefono: 'e.g. 555-1234',
    direccion: 'Address',
    descripcion: 'Description',
    moneda: 'Currency',
    formatoFecha: 'Date Format',
    zonaHoraria: 'Time Zone',
    idioma: 'Language',
    activo: 'Active',
    inactivo: 'Inactive',
    estado: 'Status',
    registro: 'Registration',
    contacto: 'Contact',
    acciones: 'Actions',
    visita: 'visit',
    visitas: 'visits',
    ultimaVisita: 'Last',
    notas: 'Notes',
    opcional: 'Optional',
    placeholderNotasCliente: 'Add additional notes about the client...',
    placeholderNotasEmpleado: 'Add additional notes about the employee...',
    
    // Botones
    guardar: 'Save',
    guardarConfiguracion: 'Save Settings',
    cancelar: 'Cancel',
    cerrar: 'Close',
    eliminar: 'Delete',
    editar: 'Edit',
    crear: 'Create',
    crearCita: 'Create Appointment',
    crearCliente: 'Create Client',
    crearServicio: 'Create Service',
    crearEmpleado: 'Create Employee',
    buscar: 'Search',
    nueva: 'New',
    nuevaCita: 'New Appointment',
    registrarse: 'Sign up',
    registrando: 'Signing up...',
    iniciarSesion: 'Sign in',
    iniciandoSesion: 'Signing in...',
    recuperar: 'Recover',
    olvidasteContrasena: 'Forgot your password?',
    noTienesCuenta: "Don't have an account?",
    crearCuenta: 'Create Account',
    rol: 'Role',
    admin: 'Admin',
    recepcionista: 'Receptionist',
    barbero: 'Barber',
    placeholderEmail: 'user@example.com',
    placeholderNombre: 'e.g. John Doe',
    placeholderEmailRegistro: 'e.g. john@email.com',
    placeholderContrasena: 'At least 6 characters',
    completarCampos: 'Please fill in all fields',
    errorIniciarSesion: 'Login error',
    errorRegistro: 'Registration error',
    datosDemo: 'or',
    
    // Citas
    cliente: 'Client',
    empleado: 'Employee',
    servicio: 'Service',
    hora: 'Time',
    dia: 'Day',
    duracion: 'Duration',
    precio: 'Price',
    detallesCita: 'Appointment Details',
    disponibilidadPersonal: 'Staff Availability',
    proximasCitas: 'Upcoming Appointments',
    horasDias: 'Time - Days',
    conflicto: 'Conflict',
    
    // Configuración
    informacionNegocio: 'Business Information',
    configuracionGeneral: 'General Settings',
    notificaciones: 'Notifications',
    recordatorioCitas: 'Appointment Reminder',
    confirmacionAutomatica: 'Automatic Confirmation',
    recordatorioHoras: 'Reminder Hours Before',
    
    // Estados
    error: 'Error',
    exito: 'Success',
    cargando: 'Loading...',
    guardando: 'Saving...',
    confirmado: 'CONFIRMED',
    pendiente: 'PENDING',
    cancelado: 'CANCELLED',
    completado: 'COMPLETED',
    completada: 'COMPLETED',
    cancelada: 'CANCELLED',
    
    // Mensajes
    guardarExitoso: 'saved successfully',
    errorAlGuardar: 'Error saving',
    requieroCamposObligatorios: 'All required fields must be filled',
    actualizar: 'Update',
    nuevoCliente: 'New Client',
    editarCliente: 'Edit Client',
    clientesTitulo: 'Clients',
    clientesSubtitulo: 'Manage your clients information',
    totalClientes: 'Total Clients',
    clientesActivos: 'Active Clients',
    visitasTotales: 'Total Visits',
    visitasPromedio: 'Average Visits',
    placeholderBuscarClientes: 'Search by name, phone or email...',
    cargandoClientes: 'Loading clients...',
    sinResultadosClientes: 'No clients found',
    sinClientes: 'No clients registered',
    confirmarEliminarCliente: 'Are you sure you want to delete this client?',
    clienteNuevoBadge: 'New client',
    clienteRegularBadge: 'Regular client',
    clienteFrecuenteBadge: '⭐ Frequent client',
    clienteVipBadge: '⭐ VIP Client',
    nuevoClienteModal: 'New Client',
    editarClienteModal: 'Edit Client',
    guardandoClienteError: 'Error creating client',
    confirmarEliminarEmpleado: 'Are you sure you want to delete this employee?',
    guardandoEmpleadoError: 'Error creating employee',

    // Servicios
    serviciosTitulo: 'Services',
    serviciosSubtitulo: 'Manage barbershop services and prices',
    totalServiciosLabel: 'Total Services',
    precioPromedio: 'Average Price',
    duracionPromedio: 'Average Duration',
    resultados: 'Results',
    placeholderBuscarServicios: 'Search by name, description or category...',
    todasCategorias: '🏷️ All categories',
    cargandoServicios: 'Loading services...',
    sinResultadosServicios: 'No services found',
    sinServicios: 'No services registered',
    precioLabel: 'Price',
    duracionLabel: 'Duration',
    nombreServicio: 'Service Name',
    categoria: 'Category',
    descripcionServicio: 'Description (Optional)',
    servicioActivo: 'Active service',
    nuevoServicio: 'New Service',
    editarServicio: 'Edit Service',
    placeholderServicioNombre: 'e.g. Classic Cut',
    placeholderPrecio: '0.00',
    placeholderDuracion: '30',
    placeholderDescripcionServicio: 'Add a description of the service...',
    confirmarEliminarServicio: 'Are you sure you want to delete this service?',
    errorCrearServicio: 'Error creating service',
    errorActualizarServicio: 'Error updating service',

    // Empleados
    empleadosTitulo: 'Staff',
    empleadosSubtitulo: 'Manage barbershop staff',
    totalPersonal: 'Total Staff',
    barberos: 'Barbers',
    recepcionistas: 'Receptionists',
    placeholderBuscarEmpleados: 'Search by name, email, phone...',
    todosRoles: '🛡️ All roles',
    cargandoEmpleados: 'Loading staff...',
    sinResultadosEmpleados: 'No staff found',
    sinEmpleados: 'No staff registered',
    nuevoEmpleado: 'New Employee',
    editarEmpleado: 'Edit Employee',
    passwordRequeridaEmpleado: 'Password is required to create a new employee',
    errorCrearEmpleado: 'Error creating employee',
    errorActualizarEmpleado: 'Error updating employee',
    contrasena: 'Password',
    mostrarContrasena: 'Show password',
    ocultarContrasena: 'Hide password',
    dejarVacioMantener: 'Leave blank to keep current',
    minimo6Caracteres: 'At least 6 characters',
    contrasenaActual: 'Current password',
    ingresarNuevaContrasena: 'Enter a new password to change the current one',
    ingresarContrasenaNuevoEmpleado: 'Enter the password for the new employee',
    fechaContratacion: 'Hire Date',
    porcentajeComision: 'Commission Percentage (%)',
    especialidad: 'Specialty',
    empleadoActivo: 'Active employee',
    soloLectura: 'Read only',
    soloPuedesCrear: 'You can only create new employees',

    // Dashboard adicionales
    ingresos: 'Revenue',
    citasCompletadasTexto: 'completed appointments',
    verTodasArrow: 'See all →',
    nuevaCitaBtn: 'New Appointment',
    nuevaCitaRapida: '📅 New Appointment',
    nuevoClienteRapido: '👥 New Client',
    verServiciosRapido: '✂️ View Services',
    verEmpleadosRapido: '👨‍💼 View Staff',
    citasHoyLabel: 'Appointments Today',
    
    // Nuevas claves para Citas y Configuración
    citasTitulo: 'Appointments',
    citasSubtitulo: 'Manage your appointments and schedules',
    editarCita: 'Edit Appointment',
    buscarCliente: 'Search Client',
    buscarClientePlaceholder: 'Search by name, phone or email...',
    crearNuevoCliente: '➕ Create New Client',
    serviciosLabel: 'Services',
    estadoLabel: 'Status',
    notasLabel: 'Notes',
    agregarNotas: 'Add additional notes...',
    seleccionarBarbero: 'Select barber...',
    seleccionarServicio: 'You must select at least one service',
    seleccionarCliente: 'You must select a client',
    barberoRequerido: 'You must select a barber',
    nombreYTelefonoRequeridos: 'Name and phone are required',
    nombreCompletoPlaceholder: 'E.g: John Doe',
    telefonoPlaceholder: 'E.g: 555-1234',
    emailOpcional: 'Email (Optional)',
    emailPlaceholder: 'E.g: john@email.com',
    cancelarBtn: 'Cancel',
    eliminarBtn: 'Delete',
    actualizarBtn: 'Update',
    guardarBtn: 'Save',
    fechaYHora: 'Date and Time',
    barberoLabel: 'Barber',
    barberoDisponiblidad: 'Staff Availability',
    filtrarPorBarbero: '🔍 Filter by Barber',
    todosBarberos: '👥 All barbers',
    limpiarFiltro: '✕ Clear filter',
    mostrando: 'Showing appointments from:',
    citasEnEstaSemana: 'appointments this week',
    misCitas: '📋 My Appointments',
    disponible: '✅ Available',
    variosBarberos: '💡 Multiple Barbers',
    variosBarberosDescripcion: 'Multiple barbers can work simultaneously at the same time. Appointments are displayed side by side in the same calendar cell.',
    barberoTieneConflicto: 'The barber already has an appointment with',
    aOtroCliente: 'another client',
    deTiempoA: 'from',
    porFavorSelecciona: 'Please select another time or barber.',
    errorAlCrearCita: 'Error creating appointment',
    errorAlActualizarCita: 'Error updating appointment',
    estasSeguroEliminarCita: 'Are you sure you want to delete this appointment?',
    confirmada: 'Confirmed',
    enProceso: 'In Progress',
    noAsistio: 'No Show',
    
    // Configuración
    horariosDeTrabajos: 'Work Hours',
    configuraLasHoras: 'Configure the opening and closing hours of the barbershop for each day of the week',
    tableDia: 'Day',
    tableApertura: 'Opening',
    tableCierre: 'Closing',
    tableEstado: 'Status',
    tableAcciones: 'Actions',
    guardarHorarios: '💾 Save Hours',
    horariosGuardadosCorrectamente: 'Hours saved successfully',
    errorGuardarHorarios: 'Error saving hours',
    informacionNegocioTabla: '🏢 Business Information',
    administraLaInformacion: "Manage your barbershop's basic information",
    nombreDelNegocio: 'Business Name *',
    nombreDelNegocioRequerido: 'Business name is required',
    descripcionBreve: 'Brief description of the business...',
    guardarInformacion: '💾 Save Information',
    informacionGuardada: 'Business information saved successfully',
    configurationGeneral: '⚙️ General Settings',
    configurarPreferencias: 'Configure general system preferences',
    monedaEtiqueta: 'Currency *',
    formatoFechaEtiqueta: 'Date Format *',
    zonaHorariaEtiqueta: 'Time Zone *',
    idiomaEtiqueta: 'Language *',
    configGeneralGuardada: 'General settings saved successfully',
    configNotificaciones: '🔔 Notification Settings',
    configurarNotificaciones: 'Configure how and when notifications are sent',
    enviarRecordatoriosCitas: '⏰ Send appointment reminders',
    horasAntesLaCita: 'Hours before the appointment to send the reminder (maximum 168 hours = 7 days)',
    configNotificacionesGuardada: 'Notification settings saved successfully',
    estasSeguroRestaurar: 'Are you sure you want to restore the default hours?',
    lunesLabel: 'Monday',
    martesLabel: 'Tuesday',
    miercolesLabel: 'Wednesday',
    juevesLabel: 'Thursday',
    viernesLabel: 'Friday',
    sabadoLabel: 'Saturday',
    domingoLabel: 'Sunday',
    soloAdminsPueden: 'Only administrators can access',
    abierto: 'Open',
    cerrado: 'Closed',
    aplicarATodos: '📋 Apply to all',
    aplicarEsteHorario: 'Apply this schedule to all days',
    restaurarPredeterminados: '🔄 Restore defaults',
  }
}

type TranslationKey = keyof typeof translations.es

export const useLanguage = () => {
  const { configuracionGeneral } = useConfiguracionStore()
  const idioma = (configuracionGeneral.idioma || 'es') as keyof typeof translations

  const t = (key: TranslationKey): string => {
    return translations[idioma][key] || translations.es[key] || key
  }

  return { t, idioma }
}
